import hiringLogoOne from '../assets/images/comlogoOne.png'
import hiringLogoTwo from '../assets/images/comlogoTwo.png'
import hiringLogoThree from '../assets/images/comlogoThree.png'
import hiringLogoFour from '../assets/images/comlogoFour.png'
import hiringLogoFive from '../assets/images/comlogoFive.png'
import hiringLogoSix from '../assets/images/comlogoSix.png'
import hiringLogoSeven from '../assets/images/comlogoSeven.png'
import hiringLogoEight from '../assets/images/comlogoEight.png'
import hiringLogoNine from '../assets/images/comlogoNine.png'
import hiringLogoTen from '../assets/images/comlogoTen.png'
import hiringLogoEleven from '../assets/images/comlogoEleven.png'
import hiringLogoTwelve from '../assets/images/comlogoTwelve.png'
import hiringLogoThirteen from '../assets/images/comlogoThirteen.png'
import hiringLogoFourteen from '../assets/images/comlogoFourteen.png'
import hiringLogoFifteen from '../assets/images/comlogoFifteen.png'
import hiringLogoSixteen from '../assets/images/comlogoSixteen.png'

export {hiringLogoOne, hiringLogoTwo, hiringLogoThree, hiringLogoFour, hiringLogoFive, hiringLogoSix, hiringLogoSeven, hiringLogoEight, hiringLogoNine, hiringLogoTen, hiringLogoEleven, hiringLogoTwelve, hiringLogoThirteen, hiringLogoFourteen, hiringLogoFifteen}